name: CI/CD Pipeline for VSCode Extension

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'VSCodeExtension/**'
      - '.github/workflows/test_and_deploy.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'VSCodeExtension/**'
      - '.github/workflows/test_and_deploy.yml'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: VSCodeExtension/code-brt

      - name: Run tests
        run: npm run test
        working-directory: VSCodeExtension/code-brt

      - name: Build project
        run: npm run build
        working-directory: VSCodeExtension/code-brt

      - name: Locate VSIX file (Windows compatible)
        id: locate-vsix
        shell: powershell
        run: |
          $vsix_file = Get-ChildItem -Path VSCodeExtension/code-brt/build -Filter *.vsix -Recurse | Select-Object -ExpandProperty FullName
          Write-Output "VSIX file located at: $vsix_file"
          echo "vsix_path=$vsix_file" >> $env:GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-artifact
          path: ${{ env.vsix_path }}
