name: CI/CD Pipeline for VSCode Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: VSCodeExtension/code-brt

      - name: Run tests
        run: npm run test
        working-directory: VSCodeExtension/code-brt

      - name: Build project
        run: npm run build:ci
        working-directory: VSCodeExtension/code-brt

      - name: Locate VSIX file
        id: locate-vsix
        run: |
          vsix_file=$(find VSCodeExtension/code-brt/build -name "*.vsix")
          echo "VSIX file located at: $vsix_file"
          echo "::set-output name=vsix_path::$vsix_file"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vsix-artifact
          path: ${{ steps.locate-vsix.outputs.vsix_path }}
