name: CI/CD Pipeline for VSCode Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: VSCodeExtension/code-brt

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build:ci

      - name: Locate VSIX file
        id: locate-vsix
        run: |
          vsix_file=$(find . -name "*.vsix")
          echo "VSIX file located at: $vsix_file"
          echo "::set-output name=vsix_path::$vsix_file"

      - name: Checkout vsix-artifacts branch
        run: |
          git fetch origin
          if git branch -r | grep -w "origin/vsix-artifacts"; then
            git checkout vsix-artifacts
            git rm -rf .
          else
            git checkout --orphan vsix-artifacts
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Move VSIX file and commit
        run: |
          mv ${{ steps.locate-vsix.outputs.vsix_path }} .
          git add *.vsix
          git commit -m "Add latest VSIX artifact"
          git push --force --set-upstream origin vsix-artifacts
